import { FileText, Heart, MessageCircle, Users } from 'lucide-react';

export const tempStats = [
  {
    icon: FileText,
    value: '23',
    label: '작성글',
    color: 'bg-blue-500',
  },
  {
    icon: MessageCircle,
    value: '89',
    label: '댓글',
    color: 'bg-green-500',
  },
  {
    icon: Heart,
    value: '456',
    label: '좋아요',
    color: 'bg-red-500',
  },
  {
    icon: Users,
    value: '1.2k',
    label: '팔로워',
    color: 'bg-purple-500',
  },
];

export const tempAlbums = [
  {
    id: 1,
    title: 'Abbey Road',
    artist: 'The Beatles',
    color: 'bg-gradient-to-br from-yellow-400 to-orange-500',
  },
  {
    id: 2,
    title: 'Dark Side',
    artist: 'Pink Floyd',
    color: 'bg-gradient-to-br from-purple-500 to-pink-500',
  },
  {
    id: 3,
    title: 'Led Zeppelin IV',
    artist: 'Led Zeppelin',
    color: 'bg-gradient-to-br from-blue-500 to-indigo-600',
  },
  {
    id: 4,
    title: 'Thriller',
    artist: 'Michael Jackson',
    color: 'bg-gradient-to-br from-red-500 to-pink-600',
  },
  {
    id: 5,
    title: 'Back in Black',
    artist: 'AC/DC',
    color: 'bg-gradient-to-br from-gray-800 to-gray-600',
  },
  {
    id: 6,
    title: 'Rumours',
    artist: 'Fleetwood Mac',
    color: 'bg-gradient-to-br from-green-500 to-teal-500',
  },
  {
    id: 7,
    title: 'Hotel California',
    artist: 'Eagles',
    color: 'bg-gradient-to-br from-amber-500 to-yellow-500',
  },
  {
    id: 8,
    title: 'Nevermind',
    artist: 'Nirvana',
    color: 'bg-gradient-to-br from-blue-600 to-cyan-500',
  },
  {
    id: 9,
    title: 'Born to Run',
    artist: 'Bruce Springsteen',
    color: 'bg-gradient-to-br from-indigo-600 to-purple-600',
  },
  {
    id: 10,
    title: 'The Wall',
    artist: 'Pink Floyd',
    color: 'bg-gradient-to-br from-slate-600 to-gray-700',
  },
  {
    id: 11,
    title: 'Kind of Blue',
    artist: 'Miles Davis',
    color: 'bg-gradient-to-br from-blue-400 to-sky-500',
  },
  {
    id: 12,
    title: "What's Going On",
    artist: 'Marvin Gaye',
    color: 'bg-gradient-to-br from-emerald-500 to-green-600',
  },
  {
    id: 13,
    title: 'Pet Sounds',
    artist: 'The Beach Boys',
    color: 'bg-gradient-to-br from-orange-400 to-red-500',
  },
  {
    id: 14,
    title: 'OK Computer',
    artist: 'Radiohead',
    color: 'bg-gradient-to-br from-violet-600 to-purple-700',
  },
  {
    id: 15,
    title: 'Are You Experienced',
    artist: 'Jimi Hendrix',
    color: 'bg-gradient-to-br from-pink-500 to-rose-600',
  },
  {
    id: 16,
    title: 'Blood on the Tracks',
    artist: 'Bob Dylan',
    color: 'bg-gradient-to-br from-red-600 to-orange-600',
  },
];

export const tempPlaylists = [
  {
    id: 1,
    title: '새벽의 감성',
    trackCount: 23,
    isPublic: true,
    likes: 45,
  },
  {
    id: 2,
    title: '드라이브 뮤직',
    trackCount: 31,
    isPublic: true,
    likes: 78,
  },
  {
    id: 3,
    title: '개인 취향',
    trackCount: 18,
    isPublic: false,
    likes: 12,
  },
  {
    id: 4,
    title: '재즈 컬렉션',
    trackCount: 27,
    isPublic: true,
    likes: 89,
  },
  {
    id: 5,
    title: '클래식 명곡',
    trackCount: 15,
    isPublic: true,
    likes: 34,
  },
  {
    id: 6,
    title: '록의 전설',
    trackCount: 42,
    isPublic: true,
    likes: 156,
  },
];

export const tempRecentDocuments = [
  {
    id: 1,
    title: 'Pink Floyd - The Wall 앨범 리뷰 작성 중',
    type: '앨범 리뷰',
    category: 'review',
    status: '작성중',
    lastModified: '2시간 전',
    views: 324,
  },
  {
    id: 2,
    title: '재즈 입문자를 위한 가이드',
    type: '음악 가이드',
    category: 'guide',
    status: '완료',
    lastModified: '1일 전',
    views: 567,
  },
  {
    id: 3,
    title: '새벽 감성 플레이리스트',
    type: '플레이리스트',
    category: 'playlist',
    status: '공개',
    lastModified: '3일 전',
    views: 892,
  },
  {
    id: 4,
    title: 'LP 관리 팁 정리',
    type: '팁 & 노하우',
    category: 'tip',
    status: '작성중',
    lastModified: '5일 전',
    views: 156,
  },
];

export const tempActivities = [
  {
    id: 1,
    type: 'listen',
    title: 'Led Zeppelin IV 앨범을 들었습니다',
    subtitle: 'Stairway to Heaven 포함 8곡 재생',
    time: '2시간 전',
    status: 'completed',
  },
  {
    id: 2,
    type: 'comment',
    title: '재즈 명반 추천 글에 댓글을 남겼습니다',
    subtitle: 'Kind of Blue는 정말 명반이죠...',
    time: '6시간 전',
    status: null,
  },
  {
    id: 3,
    type: 'like',
    title: 'Pink Floyd - The Wall 리뷰를 좋아요했습니다',
    subtitle: 'MusicCritic님의 리뷰',
    time: '1일 전',
    status: null,
  },
  {
    id: 4,
    type: 'share',
    title: '새벽 감성 플레이리스트를 공유했습니다',
    subtitle: '23곡의 감성적인 트랙 모음',
    time: '2일 전',
    status: 'completed',
  },
  {
    id: 5,
    type: 'listen',
    title: 'Abbey Road 앨범 청취 완료',
    subtitle: 'The Beatles의 대표작',
    time: '3일 전',
    status: 'completed',
  },
];

export const tempFollowingUsers = [
  {
    id: 1,
    name: 'MusicCritic',
    username: '@musiccritic',
    avatar: null,
    bio: '음악 평론가 | 클래식부터 현대음악까지',
    followers: '2.1k',
    posts: 156,
    isVerified: true,
    lastActive: '방금 전',
  },
  {
    id: 2,
    name: 'VinylCollector',
    username: '@vinylcollector',
    avatar: null,
    bio: '비닐 수집가 | 희귀 LP 전문',
    followers: '1.8k',
    posts: 89,
    isVerified: false,
    lastActive: '1시간 전',
  },
  {
    id: 3,
    name: 'JazzMaster',
    username: '@jazzmaster',
    avatar: null,
    bio: '재즈 애호가 | Blue Note Records 컬렉터',
    followers: '3.2k',
    posts: 234,
    isVerified: true,
    lastActive: '3시간 전',
  },
  {
    id: 4,
    name: 'RockLegend',
    username: '@rocklegend',
    avatar: null,
    bio: '록음악 역사 연구자',
    followers: '1.5k',
    posts: 67,
    isVerified: false,
    lastActive: '12시간 전',
  },
  {
    id: 5,
    name: 'ClassicalFan',
    username: '@classicalfan',
    avatar: null,
    bio: '클래식 음악 평론 | 오케스트라 리뷰',
    followers: '987',
    posts: 123,
    isVerified: false,
    lastActive: '1일 전',
  },
];
